_layouts:

_axes:
  - &axis_pT
    name: mdc_vtx_tracks/pT
    nb: 16
    lo: 0.0
    hi: 1.6
  - &axis_rapidity
    name: mdc_vtx_tracks/rapidity
    nb: 15
    lo: 0.01
    hi: 1.49
_cuts:
  - &protons_cuts
    mdc_vtx_tracks/pid: { equals: 2212 }
    mdc_vtx_tracks/dca_xy: {range: [-10.0, 10.0]}
    mdc_vtx_tracks/dca_z: {range: [-10.0, 10.0]}
    mdc_vtx_tracks/chi2: {range: [0.0, 100.0]}
  - &w1_cuts
    forward_wall_hits/ring: { range: [1.0, 5.0] }
    forward_wall_hits/beta: { range: [0.84, 1.0] }
    forward_wall_hits/signal: { range: [80.0, 999.0] }
  - &w2_cuts
    forward_wall_hits/ring: { range: [6.0, 7.0] }
    forward_wall_hits/beta: { range: [0.85, 1.0] }
    forward_wall_hits/signal: { range: [85.0, 999.0] }
  - &w3_cuts
    forward_wall_hits/ring: { range: [8.0, 10.0] }
    forward_wall_hits/beta: { range: [0.80, 1.0] }
    forward_wall_hits/signal: { range: [88.0, 999.0] }

hades_analysis:
  event-variables:
    - event_header/selected_tof_rpc_hits_centrality
  axes:
    - { name: event_header/selected_tof_rpc_hits_centrality, nb: 8, lo: 0.0, hi: 40 }
  q-vectors:
    - name: u
      type: track
      phi:  mdc_vtx_tracks/phi
      weight: Ones
      corrections:
        - recentering
        - twist-and-rescale
      axes:
        - *axis_pT
        - *axis_rapidity
      cuts:
        *protons_cuts
      qa:
        - {name: mdc_vtx_tracks/phi, nb: 100, lo: -4., hi: 4.}
        - *axis_pT
        - *axis_rapidity
        - [*axis_rapidity, *axis_pT]
    - name: M
      type: track
      phi:  mdc_vtx_tracks/phi
      weight: Ones
      corrections:
        - recentering
        - twist-and-rescale
      axes:
        - *axis_rapidity
      cuts:
        *protons_cuts
#        mdc_vtx_tracks/pT: { range: [0.0, 1.6] }
      qa:
        - {name: mdc_vtx_tracks/phi, nb: 100, lo: -4., hi: 4.}
        - *axis_pT
        - *axis_rapidity
        - [*axis_rapidity, *axis_pT]
    - name: W1
      type: track
      phi:  forward_wall_hits/phi
      weight: Ones
      corrections:
        - recentering
        - twist-and-rescale
      cuts:
        *w1_cuts
    - name: W2
      type: track
      phi:  forward_wall_hits/phi
      weight: Ones
      corrections:
        - recentering
        - twist-and-rescale
      cuts:
        *w2_cuts
    - name: W3
      type: track
      phi:  forward_wall_hits/phi
      weight: Ones
      corrections:
        - recentering
        - twist-and-rescale
      cuts:
        *w3_cuts