_detectors: &detectors
  - name: W1
    correction-step: RESCALED
    components: [x1,y1]
    tag: group-A
  - name: W2
    correction-step: RESCALED
    components: [x1,y1]
    tag: group-A
  - name: W3
    correction-step: RESCALED
    components: [x1,y1]
    tag: group-A

_observables:
  - method: three-sub-event
    QQ-directory: QQ/SP
    uQ-directory: uQ/SP
    u-vector: {name: u, components: [x1, y1], correction-step: RESCALED}
    EP-vectors: group-A
    resolution-vectors: group-A
    folder: "A"