language: cpp
services:
  - docker

before_install:
  docker build  --network host -t eugene274/rootcpp17_custom -f docker/Dockerfile docker

script: |
  docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/QnAnalysis eugene274/rootcpp17_custom /bin/bash -c '
  set -e # exit on failure
  set -x # trace for debug
  source /opt/rh/devtoolset-8/enable
  cd QnAnalysis
  mkdir build
  cd build
  cmake ../ -DCMAKE_BUILD_TYPE=Debug
  make
  ctest'

branches:
  only:
  - master
