//
// Created by eugene on 07/05/2021.
//

#ifndef QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_PLOT_V1_2D_HPP_
#define QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_PLOT_V1_2D_HPP_


void plot_v1_2d();


#endif //QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_PLOT_V1_2D_HPP_
