//
// Created by eugene on 07/05/2021.
//

#ifndef QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_PLOT_DV1_DY_HPP_
#define QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_PLOT_DV1_DY_HPP_

void plot_dv1_dy();

#endif //QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_PLOT_DV1_DY_HPP_
