//
// Created by eugene on 11/05/2021.
//

#ifndef QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_PLOT_V1_CENTRALITY_HPP_
#define QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_PLOT_V1_CENTRALITY_HPP_

void plot_v1_centrality();

#endif //QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_PLOT_V1_CENTRALITY_HPP_
