//
// Created by eugene on 07/05/2021.
//

#ifndef QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_PLOT_V1_PT_Y_HPP_
#define QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_PLOT_V1_PT_Y_HPP_


void plot_v1_pt_y();


#endif //QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_PLOT_V1_PT_Y_HPP_
