//
// Created by eugene on 06/05/2021.
//

#ifndef QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_REMAP_AXIS_HPP_
#define QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_REMAP_AXIS_HPP_

void remap_axes();

#endif //QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_REMAP_AXIS_HPP_
