//
// Created by eugene on 06/05/2021.
//

#ifndef QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_RESOLUTION_3SUB_HPP_
#define QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_RESOLUTION_3SUB_HPP_

void resolution_3sub();


#endif //QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_RESOLUTION_3SUB_HPP_
