//
// Created by eugene on 06/05/2021.
//

#ifndef QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_V1_COMBINE_HPP_
#define QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_V1_COMBINE_HPP_

void v1_combine();

#endif //QNANALYSIS_SRC_QNANALYSISOBSERVABLESEK_NA61_V1_COMBINE_HPP_
