//
// Created by mikhail on 10/25/20.
//

#ifndef OBSERVABLESCALCULATOR_SRC_CALCULATOR_H_
#define OBSERVABLESCALCULATOR_SRC_CALCULATOR_H_

class Calculator {

private:

};

#endif // OBSERVABLESCALCULATOR_SRC_CALCULATOR_H_
