//
// Created by mikhail on 11/23/20.
//

#ifndef QNANALYSIS_SRC_QNANALYSISOBSERVABLES_CONVERTCONFIGS_H_
#define QNANALYSIS_SRC_QNANALYSISOBSERVABLES_CONVERTCONFIGS_H_

#endif//QNANALYSIS_SRC_QNANALYSISOBSERVABLES_CONVERTCONFIGS_H_
