//
// Created by eugene on 10/12/2020.
//

#ifndef QNANALYSIS_SRC_QNANALYSISOBSERVABLES_OBSERVABLES_HPP
#define QNANALYSIS_SRC_QNANALYSISOBSERVABLES_OBSERVABLES_HPP

#include "Predicates.hpp"
#include "ResourceManager.hpp"
#include "Methods.hpp"

#endif //QNANALYSIS_SRC_QNANALYSISOBSERVABLES_OBSERVABLES_HPP
